### ISSUE TITLE
Fix authentication  

### ISSUE THREAD

**Issue by mlabadie** [H2020-IPM-openalea/agroservices#7]
For some weather resource credentials are required. meteobot, fruitdevis, metos.

exemple of request
```
ipm = IPM()

ipm.get_weatheradapter(
        endpoint='/weatheradapter/meteobot/',
        weatherStationId=732,
        ignoreErrors=True,
        interval=3600,
        timeStart='2020-06-12',
        timeEnd='2020-07-03',
        parameters=[1001],
        credentials={"username":"3138313530303239","password":"Y3Nw_48aNe4y1Z0Wj"}
)
```
in agroservice return:WARNING [agroservices:IPM]:  status is not ok with Unsupported Media Type

**Comment by christian34** [comment]
may be we have to add the chaset in the header ("application/json; charset=utf-8")
https://qastack.fr/programming/22566433/http-415-unsupported-media-type-error-with-json

But probably this has to be corrected in the webservice provider as if I understand correctly, charset should not be specified for json/application (utf-8 is mandatory for such requests)

**Comment by mlabadie** [comment]
Thanks for documentation but specification of charset utf-8 not work
